[build]
  base = "client"
  command = "bun install && bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  BUN_VERSION = "1.1.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200